<!--
  #%L
  admin base - UI Apps
  %%
  Copyright (C) 2017 headwire inc.
  %%
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at
  
  http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
  #L%
  -->
<template>
<div id="iconBrowserModal" class="pathbrowser iconbrowser modal modal-fixed-footer">
    <header class="iconbrowser-header">
        <div class="iconbrowser-options">                  
            <button  
                type="button" 
                ref="familyDropdownBtn" 
                class="dropdown-button" 
                data-activates='familyDropdown'>
                {{selectedFamily}}
            </button>
            <ul id="familyDropdown" class="dropdown-content">
                <li>
                    <a href="#!" v-on:click="selectFamily('all')">all</a>
                </li>
                <li 
                    v-for="family in families" 
                    :key="family">
                    <a href="#!" v-on:click="selectFamily(family)">{{family}}</a>
                </li>
            </ul>                
        </div>
        <div class="iconbrowser-filter">
            <input placeholder="search"  type="text" v-model="search">
        </div>
        <p class="range-field">
            <input 
                type="range" 
                min="120" 
                max="400" 
                v-model="cardSize"/>
        </p>
    </header>
        
    <div class="modal-content"> 
        <div class="col-browse">                    
            <template v-if="list && list.length > 0">
                <isotope 
                    ref="isotope" 
                    class="isotopes" 
                    v-bind:options="getIsotopeOptions()"
                    v-bind:list="list">
                    <div 
                        v-for="(icon, index) in list" 
                        :key="index">
                            <div 
                                v-if="searchFilter(icon)"
                                :class="isSelected(icon) ? 'item-icon selected' : 'item-icon'"
                                v-bind:style="`width: ${cardSize}px; height: ${cardSize}px`"
                                v-on:click.stop.prevent="selectIcon(icon)"
                                v-bind:title="icon">
                                <div class="item-content">
                                    <i
                                        v-bind:class="getIconClass(icon)"
                                        v-bind:style="`font-size: ${cardIconSize(cardSize)}px`">{{getIconText(icon)}}</i>
                                    <br/>
                                    <span class="truncate">{{icon}}</span>
                                </div>
                            </div>
                        
                    </div>
                </isotope>
            </template>
            <p v-else class="flow-text">No icons.</p>
        </div>
    </div>
    <div class="modal-footer">
        <span class="selected-path">
            <i v-if="selectedIcon" v-bind:class="getIconClass(selectedIcon)">{{getIconText(selectedIcon)}}</i> {{selectedIcon}}
        </span>
        <button type="button" class="modal-action modal-close waves-effect waves-green btn-flat" v-on:click.prevent=
        "onModalCancel">Cancel</button>
        <button type="button" class="modal-action modal-close waves-effect waves-green btn-flat" v-on:click.prevent=
        "onModalSelect">Select</button>
    </div>
</div>
</template>

<script>
    export default {
        props: ['model'],
        mounted(){
            $(this.$refs.familyDropdownBtn).dropdown({
                inDuration: 300,
                outDuration: 225,
                constrainWidth: false, // Does not change width of dropdown to that of the activator
                hover: false, // Activate on hover
                gutter: 0, // Spacing from edge
                belowOrigin: false, // Displays dropdown below the button
                alignment: 'left', // Displays dropdown with edge aligned to the left of button
                stopPropagation: false // Stops event propagation
            });
        },
        data: function() {
            return {
                filterBy: '',
                sortBy: '',
                selectedFamily: 'all',
                cardSize: 120,
                search: '',
                icons: {
                    fontAwesome: [
                        'fa-adjust',
                        'fa-adn',
                        'fa-align-center',
                        'fa-align-justify',
                        'fa-align-left',
                        'fa-align-right',
                        'fa-ambulance',
                        'fa-anchor',
                        'fa-android',
                        'fa-angle-double-down',
                        'fa-angle-double-left',
                        'fa-angle-double-right',
                        'fa-angle-double-up',
                        'fa-angle-down',
                        'fa-angle-left',
                        'fa-angle-right',
                        'fa-angle-up',
                        'fa-apple',
                        'fa-archive',
                        'fa-arrow-circle-down',
                        'fa-arrow-circle-left',
                        'fa-arrow-circle-o-down',
                        'fa-arrow-circle-o-left',
                        'fa-arrow-circle-o-right',
                        'fa-arrow-circle-o-up',
                        'fa-arrow-circle-right',
                        'fa-arrow-circle-up',
                        'fa-arrow-down',
                        'fa-arrow-left',
                        'fa-arrow-right',
                        'fa-arrow-up',
                        'fa-asterisk',
                        'fa-backward',
                        'fa-ban',
                        'fa-bar-chart-o',
                        'fa-barcode',
                        'fa-beer',
                        'fa-bell',
                        'fa-bell-o',
                        'fa-bitbucket',
                        'fa-bitbucket-square',
                        'fa-bitcoin',
                        'fa-bold',
                        'fa-bolt',
                        'fa-book',
                        'fa-bookmark',
                        'fa-bookmark-o',
                        'fa-briefcase',
                        'fa-btc',
                        'fa-bug',
                        'fa-building',
                        'fa-bullhorn',
                        'fa-bullseye',
                        'fa-calendar',
                        'fa-calendar-o',
                        'fa-camera',
                        'fa-camera-retro',
                        'fa-caret-down',
                        'fa-caret-left',
                        'fa-caret-right',
                        'fa-caret-square-o-down',
                        'fa-caret-square-o-left',
                        'fa-caret-square-o-right',
                        'fa-caret-square-o-up',
                        'fa-caret-up',
                        'fa-certificate',
                        'fa-chain',
                        'fa-chain-broken',
                        'fa-check',
                        'fa-check-circle',
                        'fa-check-circle-o',
                        'fa-check-square',
                        'fa-check-square-o',
                        'fa-chevron-circle-down',
                        'fa-chevron-circle-left',
                        'fa-chevron-circle-right',
                        'fa-chevron-circle-up',
                        'fa-chevron-down',
                        'fa-chevron-left',
                        'fa-chevron-right',
                        'fa-chevron-up',
                        'fa-circle',
                        'fa-circle-o',
                        'fa-clipboard',
                        'fa-clock-o',
                        'fa-cloud',
                        'fa-cloud-download',
                        'fa-cloud-upload',
                        'fa-cny',
                        'fa-code',
                        'fa-code-fork',
                        'fa-coffee',
                        'fa-cog',
                        'fa-cogs',
                        'fa-columns',
                        'fa-comment',
                        'fa-comment-o',
                        'fa-comments',
                        'fa-comments-o',
                        'fa-compass',
                        'fa-copy',
                        'fa-credit-card',
                        'fa-crop',
                        'fa-crosshairs',
                        'fa-css3',
                        'fa-cut',
                        'fa-cutlery',
                        'fa-dashboard',
                        'fa-dedent',
                        'fa-desktop',
                        'fa-dollar',
                        'fa-dot-circle-o',
                        'fa-download',
                        'fa-dribbble',
                        'fa-dropbox',
                        'fa-edit',
                        'fa-eject',
                        'fa-envelope',
                        'fa-envelope-o',
                        'fa-eraser',
                        'fa-eur',
                        'fa-euro',
                        'fa-exchange',
                        'fa-exclamation',
                        'fa-exclamation-circle',
                        'fa-exclamation-triangle',
                        'fa-external-link',
                        'fa-external-link-square',
                        'fa-eye',
                        'fa-eye-slash',
                        'fa-facebook',
                        'fa-facebook-square',
                        'fa-fast-backward',
                        'fa-fast-forward',
                        'fa-female',
                        'fa-fighter-jet',
                        'fa-file',
                        'fa-file-o',
                        'fa-file-text',
                        'fa-file-text-o',
                        'fa-files-o',
                        'fa-film',
                        'fa-filter',
                        'fa-fire',
                        'fa-fire-extinguisher',
                        'fa-flag',
                        'fa-flag-checkered',
                        'fa-flag-o',
                        'fa-flash',
                        'fa-flask',
                        'fa-flickr',
                        'fa-floppy-o',
                        'fa-folder',
                        'fa-folder-o',
                        'fa-folder-open',
                        'fa-folder-open-o',
                        'fa-font',
                        'fa-forward',
                        'fa-foursquare',
                        'fa-frown-o',
                        'fa-gamepad',
                        'fa-gavel',
                        'fa-gbp',
                        'fa-gear',
                        'fa-gears',
                        'fa-gift',
                        'fa-github',
                        'fa-github-alt',
                        'fa-github-square',
                        'fa-gittip',
                        'fa-glass',
                        'fa-globe',
                        'fa-google-plus',
                        'fa-google-plus-square',
                        'fa-group',
                        'fa-h-square',
                        'fa-hand-o-down',
                        'fa-hand-o-left',
                        'fa-hand-o-right',
                        'fa-hand-o-up',
                        'fa-headphones',
                        'fa-heart',
                        'fa-heart-o',
                        'fa-home',
                        'fa-html5',
                        'fa-inbox',
                        'fa-indent',
                        'fa-info',
                        'fa-info-circle',
                        'fa-inr',
                        'fa-instagram',
                        'fa-italic',
                        'fa-jpy',
                        'fa-key',
                        'fa-keyboard-o',
                        'fa-krw',
                        'fa-laptop',
                        'fa-leaf',
                        'fa-legal',
                        'fa-lemon-o',
                        'fa-level-down',
                        'fa-level-up',
                        'fa-lightbulb-o',
                        'fa-link',
                        'fa-linkedin',
                        'fa-linkedin-square',
                        'fa-linux',
                        'fa-list',
                        'fa-list-alt',
                        'fa-list-ol',
                        'fa-list-ul',
                        'fa-location-arrow',
                        'fa-lock',
                        'fa-long-arrow-down',
                        'fa-long-arrow-left',
                        'fa-long-arrow-right',
                        'fa-long-arrow-up',
                        'fa-magic',
                        'fa-magnet',
                        'fa-mail-forward',
                        'fa-mail-reply',
                        'fa-mail-reply-all',
                        'fa-male',
                        'fa-map-marker',
                        'fa-maxcdn',
                        'fa-medkit',
                        'fa-meh-o',
                        'fa-microphone',
                        'fa-microphone-slash',
                        'fa-minus',
                        'fa-minus-circle',
                        'fa-minus-square',
                        'fa-minus-square-o',
                        'fa-mobile',
                        'fa-mobile-phone',
                        'fa-money',
                        'fa-moon-o',
                        'fa-music',
                        'fa-outdent',
                        'fa-pagelines',
                        'fa-paperclip',
                        'fa-paste',
                        'fa-pause',
                        'fa-pencil',
                        'fa-pencil-square',
                        'fa-pencil-square-o',
                        'fa-phone',
                        'fa-phone-square',
                        'fa-picture-o',
                        'fa-pinterest',
                        'fa-pinterest-square',
                        'fa-plane',
                        'fa-play',
                        'fa-play-circle',
                        'fa-play-circle-o',
                        'fa-plus',
                        'fa-plus-circle',
                        'fa-plus-square',
                        'fa-power-off',
                        'fa-print',
                        'fa-puzzle-piece',
                        'fa-qrcode',
                        'fa-question',
                        'fa-question-circle',
                        'fa-quote-left',
                        'fa-quote-right',
                        'fa-random',
                        'fa-refresh',
                        'fa-renren',
                        'fa-reorder',
                        'fa-repeat',
                        'fa-reply',
                        'fa-reply-all',
                        'fa-retweet',
                        'fa-rmb',
                        'fa-road',
                        'fa-rocket',
                        'fa-rotate-left',
                        'fa-rotate-right',
                        'fa-rouble',
                        'fa-rss',
                        'fa-rss-square',
                        'fa-rub',
                        'fa-ruble',
                        'fa-rupee',
                        'fa-save',
                        'fa-scissors',
                        'fa-search',
                        'fa-search-minus',
                        'fa-search-plus',
                        'fa-share',
                        'fa-share-square',
                        'fa-share-square-o',
                        'fa-shield',
                        'fa-shopping-cart',
                        'fa-sign-in',
                        'fa-sign-out',
                        'fa-signal',
                        'fa-sitemap',
                        'fa-skype',
                        'fa-smile-o',
                        'fa-sort',
                        'fa-sort-alpha-asc',
                        'fa-sort-alpha-desc',
                        'fa-sort-amount-asc',
                        'fa-sort-amount-desc',
                        'fa-sort-asc',
                        'fa-sort-desc',
                        'fa-sort-down',
                        'fa-sort-numeric-asc',
                        'fa-sort-numeric-desc',
                        'fa-sort-up',
                        'fa-spinner',
                        'fa-square',
                        'fa-square-o',
                        'fa-stack-exchange',
                        'fa-stack-overflow',
                        'fa-star',
                        'fa-star-half',
                        'fa-star-half-empty',
                        'fa-star-half-full',
                        'fa-star-half-o',
                        'fa-star-o',
                        'fa-step-backward',
                        'fa-step-forward',
                        'fa-stethoscope',
                        'fa-stop',
                        'fa-strikethrough',
                        'fa-subscript',
                        'fa-suitcase',
                        'fa-sun-o',
                        'fa-superscript',
                        'fa-table',
                        'fa-tablet',
                        'fa-tachometer',
                        'fa-tag',
                        'fa-tags',
                        'fa-tasks',
                        'fa-terminal',
                        'fa-text-height',
                        'fa-text-width',
                        'fa-th',
                        'fa-th-large',
                        'fa-th-list',
                        'fa-thumb-tack',
                        'fa-thumbs-down',
                        'fa-thumbs-o-down',
                        'fa-thumbs-o-up',
                        'fa-thumbs-up',
                        'fa-ticket',
                        'fa-times',
                        'fa-times-circle',
                        'fa-times-circle-o',
                        'fa-tint',
                        'fa-toggle-down',
                        'fa-toggle-left',
                        'fa-toggle-right',
                        'fa-toggle-up',
                        'fa-trash-o',
                        'fa-trello',
                        'fa-trophy',
                        'fa-truck',
                        'fa-try',
                        'fa-tumblr',
                        'fa-tumblr-square',
                        'fa-turkish-lira',
                        'fa-twitter',
                        'fa-twitter-square',
                        'fa-umbrella',
                        'fa-underline',
                        'fa-undo',
                        'fa-unlink',
                        'fa-unlock',
                        'fa-unsorted',
                        'fa-upload',
                        'fa-usd',
                        'fa-user',
                        'fa-user-md',
                        'fa-video-camera',
                        'fa-vimeo-square',
                        'fa-vk',
                        'fa-volume-down',
                        'fa-volume-off',
                        'fa-volume-up',
                        'fa-warning',
                        'fa-weibo',
                        'fa-wheelchair',
                        'fa-windows',
                        'fa-won',
                        'fa-wrench',
                        'fa-xing',
                        'fa-xing-square',
                        'fa-yen',
                        'fa-youtube',
                        'fa-youtube-play',
                        'fa-youtube-square'
                    ],
                    material:[
                        '3d_rotation',
                        'accessibility',
                        'accessible',
                        'account_balance',
                        'account_balance_wallet',
                        'account_box',
                        'account_circle',
                        'add_shopping_cart',
                        'alarm',
                        'alarm_add',
                        'alarm_off',
                        'alarm_on',
                        'all_out',
                        'android',
                        'announcement',
                        'aspect_ratio',
                        'assessment',
                        'assignment',
                        'assignment_ind',
                        'assignment_late',
                        'assignment_return',
                        'assignment_returned',
                        'assignment_turned_in',
                        'autorenew',
                        'backup',
                        'book',
                        'bookmark',
                        'bookmark_border',
                        'bug_report',
                        'build',
                        'cached',
                        'camera_enhance',
                        'card_giftcard',
                        'card_membership',
                        'card_travel',
                        'change_history',
                        'check_circle',
                        'chrome_reader_mode',
                        'class',
                        'code',
                        'compare_arrows',
                        'copyright',
                        'credit_card',
                        'dashboard',
                        'date_range',
                        'delete',
                        'delete_forever',
                        'description',
                        'dns',
                        'done',
                        'done_all',
                        'donut_large',
                        'donut_small',
                        'eject',
                        'euro_symbol',
                        'event',
                        'event_seat',
                        'exit_to_app',
                        'explore',
                        'extension',
                        'face',
                        'favorite',
                        'favorite_border',
                        'feedback',
                        'find_in_page',
                        'find_replace',
                        'fingerprint',
                        'flight_land',
                        'flight_takeoff',
                        'flip_to_back',
                        'flip_to_front',
                        'g_translate',
                        'gavel',
                        'get_app',
                        'gif',
                        'grade',
                        'group_work',
                        'help',
                        'help_outline',
                        'highlight_off',
                        'history',
                        'home',
                        'hourglass_empty',
                        'hourglass_full',
                        'http',
                        'https',
                        'important_devices',
                        'info',
                        'info_outline',
                        'input',
                        'invert_colors',
                        'label',
                        'label_outline',
                        'language',
                        'launch',
                        'lightbulb_outline',
                        'line_style',
                        'line_weight',
                        'list',
                        'lock',
                        'lock_open',
                        'lock_outline',
                        'loyalty',
                        'markunread_mailbox',
                        'motorcycle',
                        'note_add',
                        'offline_pin',
                        'opacity',
                        'open_in_browser',
                        'open_in_new',
                        'open_with',
                        'pageview',
                        'pan_tool',
                        'payment',
                        'perm_camera_mic',
                        'perm_contact_calendar',
                        'perm_data_setting',
                        'perm_device_information',
                        'perm_identity',
                        'perm_media',
                        'perm_phone_msg',
                        'perm_scan_wifi',
                        'pets',
                        'picture_in_picture',
                        'picture_in_picture_alt',
                        'play_for_work',
                        'polymer',
                        'power_settings_new',
                        'pregnant_woman',
                        'print',
                        'query_builder',
                        'question_answer',
                        'receipt',
                        'record_voice_over',
                        'redeem',
                        'remove_shopping_cart',
                        'reorder',
                        'report_problem',
                        'restore',
                        'restore_page',
                        'room',
                        'rounded_corner',
                        'rowing',
                        'schedule',
                        'search',
                        'settings',
                        'settings_applications',
                        'settings_backup_restore',
                        'settings_bluetooth',
                        'settings_brightness',
                        'settings_cell',
                        'settings_ethernet'
                    ],
                    ionicons: [
                        'ion-alert',
                        'ion-alert-circled',
                        'ion-android-add',
                        'ion-android-add-circle',
                        'ion-android-alarm-clock',
                        'ion-android-alert',
                        'ion-android-apps',
                        'ion-android-archive',
                        'ion-android-arrow-back',
                        'ion-android-arrow-down',
                        'ion-android-arrow-dropdown',
                        'ion-android-arrow-dropdown-circle',
                        'ion-android-arrow-dropleft',
                        'ion-android-arrow-dropleft-circle',
                        'ion-android-arrow-dropright',
                        'ion-android-arrow-dropright-circle',
                        'ion-android-arrow-dropup',
                        'ion-android-arrow-dropup-circle',
                        'ion-android-arrow-forward',
                        'ion-android-arrow-up',
                        'ion-android-attach',
                        'ion-android-bar',
                        'ion-android-bicycle',
                        'ion-android-boat',
                        'ion-android-bookmark',
                        'ion-android-bulb',
                        'ion-android-bus',
                        'ion-android-calendar',
                        'ion-android-call',
                        'ion-android-camera',
                        'ion-android-cancel',
                        'ion-android-car',
                        'ion-android-cart',
                        'ion-android-chat',
                        'ion-android-checkbox',
                        'ion-android-checkbox-blank',
                        'ion-android-checkbox-outline',
                        'ion-android-checkbox-outline-blank',
                        'ion-android-checkmark-circle',
                        'ion-android-clipboard',
                        'ion-android-close',
                        'ion-android-cloud',
                        'ion-android-cloud-circle',
                        'ion-android-cloud-done',
                        'ion-android-cloud-outline',
                        'ion-android-color-palette',
                        'ion-android-compass',
                        'ion-android-contact',
                        'ion-android-contacts',
                        'ion-android-contract',
                        'ion-android-create',
                        'ion-android-delete',
                        'ion-android-desktop',
                        'ion-android-document',
                        'ion-android-done',
                        'ion-android-done-all',
                        'ion-android-download',
                        'ion-android-drafts',
                        'ion-android-exit',
                        'ion-android-expand',
                        'ion-android-favorite',
                        'ion-android-favorite-outline',
                        'ion-android-film',
                        'ion-android-folder',
                        'ion-android-folder-open',
                        'ion-android-funnel',
                        'ion-android-globe',
                        'ion-android-hand',
                        'ion-android-hangout',
                        'ion-android-happy',
                        'ion-android-home',
                        'ion-android-image',
                        'ion-android-laptop',
                        'ion-android-list',
                        'ion-android-locate',
                        'ion-android-lock',
                        'ion-android-mail',
                        'ion-android-map',
                        'ion-android-menu',
                        'ion-android-microphone',
                        'ion-android-microphone-off',
                        'ion-android-more-horizontal',
                        'ion-android-more-vertical',
                        'ion-android-navigate',
                        'ion-android-notifications',
                        'ion-android-notifications-none',
                        'ion-android-notifications-off',
                        'ion-android-open',
                        'ion-android-options',
                        'ion-android-people',
                        'ion-android-person',
                        'ion-android-person-add',
                        'ion-android-phone-landscape',
                        'ion-android-phone-portrait',
                        'ion-android-pin',
                        'ion-android-plane',
                        'ion-android-playstore',
                        'ion-android-print',
                        'ion-android-radio-button-off',
                        'ion-android-radio-button-on',
                        'ion-android-refresh',
                        'ion-android-remove',
                        'ion-android-remove-circle',
                        'ion-android-restaurant',
                        'ion-android-sad',
                        'ion-android-search',
                        'ion-android-send',
                        'ion-android-settings',
                        'ion-android-share',
                        'ion-android-share-alt',
                        'ion-android-star',
                        'ion-android-star-half',
                        'ion-android-star-outline',
                        'ion-android-stopwatch',
                        'ion-android-subway',
                        'ion-android-sunny',
                        'ion-android-sync',
                        'ion-android-textsms',
                        'ion-android-time',
                        'ion-android-train',
                        'ion-android-unlock',
                        'ion-android-upload',
                        'ion-android-volume-down',
                        'ion-android-volume-mute',
                        'ion-android-volume-off',
                        'ion-android-volume-up',
                        'ion-android-walk',
                        'ion-android-warning',
                        'ion-android-watch',
                        'ion-android-wifi',
                        'ion-aperture',
                        'ion-archive',
                        'ion-arrow-down-a',
                        'ion-arrow-down-b',
                        'ion-arrow-down-c',
                        'ion-arrow-expand',
                        'ion-arrow-graph-down-left',
                        'ion-arrow-graph-down-right',
                        'ion-arrow-graph-up-left',
                        'ion-arrow-graph-up-right',
                        'ion-arrow-left-a',
                        'ion-arrow-left-b',
                        'ion-arrow-left-c',
                        'ion-arrow-move',
                        'ion-arrow-resize',
                        'ion-arrow-return-left',
                        'ion-arrow-return-right',
                        'ion-arrow-right-a',
                        'ion-arrow-right-b',
                        'ion-arrow-right-c',
                        'ion-arrow-shrink',
                        'ion-arrow-swap',
                        'ion-arrow-up-a',
                        'ion-arrow-up-b',
                        'ion-arrow-up-c',
                        'ion-asterisk',
                        'ion-at',
                        'ion-backspace',
                        'ion-backspace-outline',
                        'ion-bag',
                        'ion-battery-charging',
                        'ion-battery-empty',
                        'ion-battery-full',
                        'ion-battery-half',
                        'ion-battery-low',
                        'ion-beaker',
                        'ion-beer',
                        'ion-bluetooth',
                        'ion-bonfire',
                        'ion-bookmark',
                        'ion-bowtie',
                        'ion-briefcase',
                        'ion-bug',
                        'ion-calculator',
                        'ion-calendar',
                        'ion-camera',
                        'ion-card',
                        'ion-cash',
                        'ion-chatbox',
                        'ion-chatbox-working',
                        'ion-chatboxes',
                        'ion-chatbubble',
                        'ion-chatbubble-working',
                        'ion-chatbubbles',
                        'ion-checkmark',
                        'ion-checkmark-circled',
                        'ion-checkmark-round',
                        'ion-chevron-down',
                        'ion-chevron-left',
                        'ion-chevron-right',
                        'ion-chevron-up',
                        'ion-clipboard',
                        'ion-clock',
                        'ion-close',
                        'ion-close-circled',
                        'ion-close-round',
                        'ion-closed-captioning',
                        'ion-cloud',
                        'ion-code',
                        'ion-code-download',
                        'ion-code-working',
                        'ion-coffee',
                        'ion-compass',
                        'ion-compose',
                        'ion-connection-bars',
                        'ion-contrast',
                        'ion-crop',
                        'ion-cube',
                        'ion-disc',
                        'ion-document',
                        'ion-document-text',
                        'ion-drag',
                        'ion-earth',
                        'ion-easel',
                        'ion-edit',
                        'ion-egg',
                        'ion-eject',
                        'ion-email',
                        'ion-email-unread',
                        'ion-erlenmeyer-flask',
                        'ion-erlenmeyer-flask-bubbles',
                        'ion-eye',
                        'ion-eye-disabled',
                        'ion-female',
                        'ion-filing',
                        'ion-film-marker',
                        'ion-fireball',
                        'ion-flag',
                        'ion-flame',
                        'ion-flash',
                        'ion-flash-off',
                        'ion-folder',
                        'ion-fork',
                        'ion-fork-repo',
                        'ion-forward',
                        'ion-funnel',
                        'ion-gear-a',
                        'ion-gear-b',
                        'ion-grid',
                        'ion-hammer',
                        'ion-happy',
                        'ion-happy-outline',
                        'ion-headphone',
                        'ion-heart',
                        'ion-heart-broken',
                        'ion-help',
                        'ion-help-buoy',
                        'ion-help-circled',
                        'ion-home',
                        'ion-icecream',
                        'ion-image',
                        'ion-images',
                        'ion-information',
                        'ion-information-circled',
                        'ion-ionic',
                        'ion-ios-alarm',
                        'ion-ios-alarm-outline',
                        'ion-ios-albums',
                        'ion-ios-albums-outline',
                        'ion-ios-americanfootball',
                        'ion-ios-americanfootball-outline',
                        'ion-ios-analytics',
                        'ion-ios-analytics-outline',
                        'ion-ios-arrow-back',
                        'ion-ios-arrow-down',
                        'ion-ios-arrow-forward',
                        'ion-ios-arrow-left',
                        'ion-ios-arrow-right',
                        'ion-ios-arrow-thin-down',
                        'ion-ios-arrow-thin-left',
                        'ion-ios-arrow-thin-right',
                        'ion-ios-arrow-thin-up',
                        'ion-ios-arrow-up',
                        'ion-ios-at',
                        'ion-ios-at-outline',
                        'ion-ios-barcode',
                        'ion-ios-barcode-outline',
                        'ion-ios-baseball',
                        'ion-ios-baseball-outline',
                        'ion-ios-basketball',
                        'ion-ios-basketball-outline',
                        'ion-ios-bell',
                        'ion-ios-bell-outline',
                        'ion-ios-body',
                        'ion-ios-body-outline',
                        'ion-ios-bolt',
                        'ion-ios-bolt-outline',
                        'ion-ios-book',
                        'ion-ios-book-outline',
                        'ion-ios-bookmarks',
                        'ion-ios-bookmarks-outline',
                        'ion-ios-box',
                        'ion-ios-box-outline',
                        'ion-ios-briefcase',
                        'ion-ios-briefcase-outline',
                        'ion-ios-browsers',
                        'ion-ios-browsers-outline',
                        'ion-ios-calculator',
                        'ion-ios-calculator-outline',
                        'ion-ios-calendar',
                        'ion-ios-calendar-outline',
                        'ion-ios-camera',
                        'ion-ios-camera-outline',
                        'ion-ios-cart',
                        'ion-ios-cart-outline',
                        'ion-ios-chatboxes',
                        'ion-ios-chatboxes-outline',
                        'ion-ios-chatbubble',
                        'ion-ios-chatbubble-outline',
                        'ion-ios-checkmark',
                        'ion-ios-checkmark-empty',
                        'ion-ios-checkmark-outline',
                        'ion-ios-circle-filled',
                        'ion-ios-circle-outline',
                        'ion-ios-clock',
                        'ion-ios-clock-outline',
                        'ion-ios-close',
                        'ion-ios-close-empty',
                        'ion-ios-close-outline',
                        'ion-ios-cloud',
                        'ion-ios-cloud-download',
                        'ion-ios-cloud-download-outline',
                        'ion-ios-cloud-outline',
                        'ion-ios-cloud-upload',
                        'ion-ios-cloud-upload-outline',
                        'ion-ios-cloudy',
                        'ion-ios-cloudy-night',
                        'ion-ios-cloudy-night-outline',
                        'ion-ios-cloudy-outline',
                        'ion-ios-cog',
                        'ion-ios-cog-outline',
                        'ion-ios-color-filter',
                        'ion-ios-color-filter-outline',
                        'ion-ios-color-wand',
                        'ion-ios-color-wand-outline',
                        'ion-ios-compose',
                        'ion-ios-compose-outline',
                        'ion-ios-contact',
                        'ion-ios-contact-outline',
                        'ion-ios-copy',
                        'ion-ios-copy-outline',
                        'ion-ios-crop',
                        'ion-ios-crop-strong',
                        'ion-ios-download',
                        'ion-ios-download-outline',
                        'ion-ios-drag',
                        'ion-ios-email',
                        'ion-ios-email-outline',
                        'ion-ios-eye',
                        'ion-ios-eye-outline',
                        'ion-ios-fastforward',
                        'ion-ios-fastforward-outline',
                        'ion-ios-filing',
                        'ion-ios-filing-outline',
                        'ion-ios-film',
                        'ion-ios-film-outline',
                        'ion-ios-flag',
                        'ion-ios-flag-outline',
                        'ion-ios-flame',
                        'ion-ios-flame-outline',
                        'ion-ios-flask',
                        'ion-ios-flask-outline',
                        'ion-ios-flower',
                        'ion-ios-flower-outline',
                        'ion-ios-folder',
                        'ion-ios-folder-outline',
                        'ion-ios-football',
                        'ion-ios-football-outline',
                        'ion-ios-game-controller-a',
                        'ion-ios-game-controller-a-outline',
                        'ion-ios-game-controller-b',
                        'ion-ios-game-controller-b-outline',
                        'ion-ios-gear',
                        'ion-ios-gear-outline',
                        'ion-ios-glasses',
                        'ion-ios-glasses-outline',
                        'ion-ios-grid-view',
                        'ion-ios-grid-view-outline',
                        'ion-ios-heart',
                        'ion-ios-heart-outline',
                        'ion-ios-help',
                        'ion-ios-help-empty',
                        'ion-ios-help-outline',
                        'ion-ios-home',
                        'ion-ios-home-outline',
                        'ion-ios-infinite',
                        'ion-ios-infinite-outline',
                        'ion-ios-information',
                        'ion-ios-information-empty',
                        'ion-ios-information-outline',
                        'ion-ios-ionic-outline',
                        'ion-ios-keypad',
                        'ion-ios-keypad-outline',
                        'ion-ios-lightbulb',
                        'ion-ios-lightbulb-outline',
                        'ion-ios-list',
                        'ion-ios-list-outline',
                        'ion-ios-location',
                        'ion-ios-location-outline',
                        'ion-ios-locked',
                        'ion-ios-locked-outline',
                        'ion-ios-loop',
                        'ion-ios-loop-strong',
                        'ion-ios-medical',
                        'ion-ios-medical-outline',
                        'ion-ios-medkit',
                        'ion-ios-medkit-outline',
                        'ion-ios-mic',
                        'ion-ios-mic-off',
                        'ion-ios-mic-outline',
                        'ion-ios-minus',
                        'ion-ios-minus-empty',
                        'ion-ios-minus-outline',
                        'ion-ios-monitor',
                        'ion-ios-monitor-outline',
                        'ion-ios-moon',
                        'ion-ios-moon-outline',
                        'ion-ios-more',
                        'ion-ios-more-outline',
                        'ion-ios-musical-note',
                        'ion-ios-musical-notes',
                        'ion-ios-navigate',
                        'ion-ios-navigate-outline',
                        'ion-ios-nutrition',
                        'ion-ios-nutrition-outline',
                        'ion-ios-paper',
                        'ion-ios-paper-outline',
                        'ion-ios-paperplane',
                        'ion-ios-paperplane-outline',
                        'ion-ios-partlysunny',
                        'ion-ios-partlysunny-outline',
                        'ion-ios-pause',
                        'ion-ios-pause-outline',
                        'ion-ios-paw',
                        'ion-ios-paw-outline',
                        'ion-ios-people',
                        'ion-ios-people-outline',
                        'ion-ios-person',
                        'ion-ios-person-outline',
                        'ion-ios-personadd',
                        'ion-ios-personadd-outline',
                        'ion-ios-photos',
                        'ion-ios-photos-outline',
                        'ion-ios-pie',
                        'ion-ios-pie-outline',
                        'ion-ios-pint',
                        'ion-ios-pint-outline',
                        'ion-ios-play',
                        'ion-ios-play-outline',
                        'ion-ios-plus',
                        'ion-ios-plus-empty',
                        'ion-ios-plus-outline',
                        'ion-ios-pricetag',
                        'ion-ios-pricetag-outline',
                        'ion-ios-pricetags',
                        'ion-ios-pricetags-outline',
                        'ion-ios-printer',
                        'ion-ios-printer-outline',
                        'ion-ios-pulse',
                        'ion-ios-pulse-strong',
                        'ion-ios-rainy',
                        'ion-ios-rainy-outline',
                        'ion-ios-recording',
                        'ion-ios-recording-outline',
                        'ion-ios-redo',
                        'ion-ios-redo-outline',
                        'ion-ios-refresh',
                        'ion-ios-refresh-empty',
                        'ion-ios-refresh-outline',
                        'ion-ios-reload',
                        'ion-ios-reverse-camera',
                        'ion-ios-reverse-camera-outline',
                        'ion-ios-rewind',
                        'ion-ios-rewind-outline',
                        'ion-ios-rose',
                        'ion-ios-rose-outline',
                        'ion-ios-search',
                        'ion-ios-search-strong',
                        'ion-ios-settings',
                        'ion-ios-settings-strong',
                        'ion-ios-shuffle',
                        'ion-ios-shuffle-strong',
                        'ion-ios-skipbackward',
                        'ion-ios-skipbackward-outline',
                        'ion-ios-skipforward',
                        'ion-ios-skipforward-outline',
                        'ion-ios-snowy',
                        'ion-ios-speedometer',
                        'ion-ios-speedometer-outline',
                        'ion-ios-star',
                        'ion-ios-star-half',
                        'ion-ios-star-outline',
                        'ion-ios-stopwatch',
                        'ion-ios-stopwatch-outline',
                        'ion-ios-sunny',
                        'ion-ios-sunny-outline',
                        'ion-ios-telephone',
                        'ion-ios-telephone-outline',
                        'ion-ios-tennisball',
                        'ion-ios-tennisball-outline',
                        'ion-ios-thunderstorm',
                        'ion-ios-thunderstorm-outline',
                        'ion-ios-time',
                        'ion-ios-time-outline',
                        'ion-ios-timer',
                        'ion-ios-timer-outline',
                        'ion-ios-toggle',
                        'ion-ios-toggle-outline',
                        'ion-ios-trash',
                        'ion-ios-trash-outline',
                        'ion-ios-undo',
                        'ion-ios-undo-outline',
                        'ion-ios-unlocked',
                        'ion-ios-unlocked-outline',
                        'ion-ios-upload',
                        'ion-ios-upload-outline',
                        'ion-ios-videocam',
                        'ion-ios-videocam-outline',
                        'ion-ios-volume-high',
                        'ion-ios-volume-low',
                        'ion-ios-wineglass',
                        'ion-ios-wineglass-outline',
                        'ion-ios-world',
                        'ion-ios-world-outline',
                        'ion-ipad',
                        'ion-iphone',
                        'ion-ipod',
                        'ion-jet',
                        'ion-key',
                        'ion-knife',
                        'ion-laptop',
                        'ion-leaf',
                        'ion-levels',
                        'ion-lightbulb',
                        'ion-link',
                        'ion-load-a',
                        'ion-load-b',
                        'ion-load-c',
                        'ion-load-d',
                        'ion-location',
                        'ion-lock-combination',
                        'ion-locked',
                        'ion-log-in',
                        'ion-log-out',
                        'ion-loop',
                        'ion-magnet',
                        'ion-male',
                        'ion-man',
                        'ion-map',
                        'ion-medkit',
                        'ion-merge',
                        'ion-mic-a',
                        'ion-mic-b',
                        'ion-mic-c',
                        'ion-minus',
                        'ion-minus-circled',
                        'ion-minus-round',
                        'ion-model-s',
                        'ion-monitor',
                        'ion-more',
                        'ion-mouse',
                        'ion-music-note',
                        'ion-navicon',
                        'ion-navicon-round',
                        'ion-navigate',
                        'ion-network',
                        'ion-no-smoking',
                        'ion-nuclear',
                        'ion-outlet',
                        'ion-paintbrush',
                        'ion-paintbucket',
                        'ion-paper-airplane',
                        'ion-paperclip',
                        'ion-pause',
                        'ion-person',
                        'ion-person-add',
                        'ion-person-stalker',
                        'ion-pie-graph',
                        'ion-pin',
                        'ion-pinpoint',
                        'ion-pizza',
                        'ion-plane',
                        'ion-planet',
                        'ion-play',
                        'ion-playstation',
                        'ion-plus',
                        'ion-plus-circled',
                        'ion-plus-round',
                        'ion-podium',
                        'ion-pound',
                        'ion-power',
                        'ion-pricetag',
                        'ion-pricetags',
                        'ion-printer',
                        'ion-pull-request',
                        'ion-qr-scanner',
                        'ion-quote',
                        'ion-radio-waves',
                        'ion-record',
                        'ion-refresh',
                        'ion-reply',
                        'ion-reply-all',
                        'ion-ribbon-a',
                        'ion-ribbon-b',
                        'ion-sad',
                        'ion-sad-outline',
                        'ion-scissors',
                        'ion-search',
                        'ion-settings',
                        'ion-share',
                        'ion-shuffle',
                        'ion-skip-backward',
                        'ion-skip-forward',
                        'ion-social-android',
                        'ion-social-android-outline',
                        'ion-social-angular',
                        'ion-social-angular-outline',
                        'ion-social-apple',
                        'ion-social-apple-outline',
                        'ion-social-bitcoin',
                        'ion-social-bitcoin-outline',
                        'ion-social-buffer',
                        'ion-social-buffer-outline',
                        'ion-social-chrome',
                        'ion-social-chrome-outline',
                        'ion-social-codepen',
                        'ion-social-codepen-outline',
                        'ion-social-css3',
                        'ion-social-css3-outline',
                        'ion-social-designernews',
                        'ion-social-designernews-outline',
                        'ion-social-dribbble',
                        'ion-social-dribbble-outline',
                        'ion-social-dropbox',
                        'ion-social-dropbox-outline',
                        'ion-social-euro',
                        'ion-social-euro-outline',
                        'ion-social-facebook',
                        'ion-social-facebook-outline',
                        'ion-social-foursquare',
                        'ion-social-foursquare-outline',
                        'ion-social-freebsd-devil',
                        'ion-social-github',
                        'ion-social-github-outline',
                        'ion-social-google',
                        'ion-social-google-outline',
                        'ion-social-googleplus',
                        'ion-social-googleplus-outline',
                        'ion-social-hackernews',
                        'ion-social-hackernews-outline',
                        'ion-social-html5',
                        'ion-social-html5-outline',
                        'ion-social-instagram',
                        'ion-social-instagram-outline',
                        'ion-social-javascript',
                        'ion-social-javascript-outline',
                        'ion-social-linkedin',
                        'ion-social-linkedin-outline',
                        'ion-social-markdown',
                        'ion-social-nodejs',
                        'ion-social-octocat',
                        'ion-social-pinterest',
                        'ion-social-pinterest-outline',
                        'ion-social-python',
                        'ion-social-reddit',
                        'ion-social-reddit-outline',
                        'ion-social-rss',
                        'ion-social-rss-outline',
                        'ion-social-sass',
                        'ion-social-skype',
                        'ion-social-skype-outline',
                        'ion-social-snapchat',
                        'ion-social-snapchat-outline',
                        'ion-social-tumblr',
                        'ion-social-tumblr-outline',
                        'ion-social-tux',
                        'ion-social-twitch',
                        'ion-social-twitch-outline',
                        'ion-social-twitter',
                        'ion-social-twitter-outline',
                        'ion-social-usd',
                        'ion-social-usd-outline',
                        'ion-social-vimeo',
                        'ion-social-vimeo-outline',
                        'ion-social-whatsapp',
                        'ion-social-whatsapp-outline',
                        'ion-social-windows',
                        'ion-social-windows-outline',
                        'ion-social-wordpress',
                        'ion-social-wordpress-outline',
                        'ion-social-yahoo',
                        'ion-social-yahoo-outline',
                        'ion-social-yen',
                        'ion-social-yen-outline',
                        'ion-social-youtube',
                        'ion-social-youtube-outline',
                        'ion-soup-can',
                        'ion-soup-can-outline',
                        'ion-speakerphone',
                        'ion-speedometer',
                        'ion-spoon',
                        'ion-star',
                        'ion-stats-bars',
                        'ion-steam',
                        'ion-stop',
                        'ion-thermometer',
                        'ion-thumbsdown',
                        'ion-thumbsup',
                        'ion-toggle',
                        'ion-toggle-filled',
                        'ion-transgender',
                        'ion-trash-a',
                        'ion-trash-b',
                        'ion-trophy',
                        'ion-tshirt',
                        'ion-tshirt-outline',
                        'ion-umbrella',
                        'ion-university',
                        'ion-unlocked',
                        'ion-upload',
                        'ion-usb',
                        'ion-videocamera',
                        'ion-volume-high',
                        'ion-volume-low',
                        'ion-volume-medium',
                        'ion-volume-mute',
                        'ion-wand',
                        'ion-waterdrop',
                        'ion-wifi',
                        'ion-wineglass',
                        'ion-woman',
                        'ion-wrench',
                        'ion-xbox'
                    ]
                }
            }
        },
        watch: {
            cardSize: function (newCardSize) {
                this.updateIsotopeLayout('masonry')
            },
            search: function (newSearch) {
                this.updateIsotopeLayout('masonry')
            }
        },
        computed: {
            selectedIcon(){
                let iconFamily = $perAdminApp.getNodeFromViewOrNull('/state/iconbrowser/family')
                if(iconFamily === 'material'){
                    return $perAdminApp.getNodeFromViewOrNull('/state/iconbrowser/text')
                }
                let iconClass = $perAdminApp.getNodeFromViewOrNull('/state/iconbrowser/class')
                return iconClass
            },
            families(){
                return $perAdminApp.getNodeFromViewOrNull('/state/iconbrowser/families')
            },
            list(){
                var selectedFamily = this.camelize(this.selectedFamily)
                if(selectedFamily === 'all'){
                    var icons = []
                    for (var property in this.icons) {
                        if (this.icons.hasOwnProperty(property)) {
                            icons = icons.concat(this.icons[property])
                        }
                    }
                    // console.log('icons: ', icons)
                    return icons
                } else {
                    return this.icons[selectedFamily]
                }
            }
        },
        methods: {
            iconBrowserModalOpen(that, options) {
                $('#iconBrowserModal').modal('open', options)
                Vue.nextTick(function () {
                    that.$refs.isotope.layout('masonry')
                })
            },
            searchFilter(icon) {
                if(this.search.length === 0) return true
                return (icon.indexOf(this.search) >= 0)
            },
            selectFamily(family){
                this.selectedFamily = family
            },
            isSelected(iconClass) {
                let selectedIconName = this.getIconNameFromClass(this.selectedIcon)
                return selectedIconName === iconClass
            },
            selectIcon(icon) {
                $perAdminApp.getNodeFromView('/state/iconbrowser').family = this.getIconFamily(icon)
                $perAdminApp.getNodeFromView('/state/iconbrowser').class = this.getIconClass(icon)
                $perAdminApp.getNodeFromView('/state/iconbrowser').text = this.getIconText(icon)
            },
            getIconNameFromClass(iconClass){
                if(iconClass || iconClass !== null){
                    var hasWhiteSpace = iconClass.includes(' ')
                    if(!hasWhiteSpace) return iconClass
                    // if iconClass has white space, icon name is last part (fa fa-add)
                    let iconClasses = iconClass.split(' ')
                    let len = iconClasses.length
                    let lastClass = iconClasses[len - 1]
                    return lastClass
                }
            },
            cardIconSize: function(cardSize){
                return Math.floor(cardSize/3)
            },
            updateIsotopeLayout: function(layout){
                this.$nextTick(function () {
                    this.$refs.isotope.layout(layout)
                })
            },
            getIconFamily(icon){
                var iconFamily
                switch(true) {
                    case (icon.includes('_')):
                        iconFamily = 'material'
                        break
                    case (icon.includes('fa')):
                        iconFamily = 'fontAwesome'
                        break
                    case (icon.includes('ion')):
                        iconFamily = 'ionicons'
                        break
                    default:
                        iconFamily = 'material'
                }
                return iconFamily
            },
            getIconClass(icon) {
                var iconClass
                switch(true) {
                    case (icon.includes('_')):
                        iconClass = 'material-icons'
                        break
                    case (icon.includes('fa')):
                        iconClass = 'fa ' + icon
                        break

                    case (icon.includes('ion')):
                        iconClass = icon
                        break
                    default:
                        iconClass = 'material-icons'
                }
                return iconClass
            },
            getIconText(icon){
                if(this.getIconClass(icon) === 'material-icons'){
                    return icon
                }
                return ''
            },
            getIsotopeOptions: function() {
                return {
                    layoutMode: 'masonry',
                    itemSelector: '.item',
                    masonry: {
                        gutter: 15
                    }
                    ,
                    getSortData: {
                        icon: function(icon){
                            return icon.toLowerCase()    
                        },
                        // family: function(icon){
                        //     return Date.parse(itemElem.created)
                        // }
                    },
                    getFilterData:{
                        fontAwesome: icon => this.getIconClass(icon) === ('fa ' + icon),
                        materialDesign: icon => this.getIconClass(icon) === 'material-icons'
                    }
                }
            },
            onSort(sortType){
                this.sortBy = sortType
                this.$refs.isotope.sort(sortType)
            },
            onFilter(filterType){
                this.filterBy = filterType
                this.$refs.isotope.filter(filterType)
            },
            camelize(str) {
                return str.replace(/(?:^\w|[A-Z]|\b\w)/g, function(letter, index) {
                    return index == 0 ? letter.toLowerCase() : letter.toUpperCase();
                }).replace(/\s+/g, '');
            },
            getIconParts(iconValue){
                let iconParts = iconValue.split(':') //[iconFamily, iconClass, iconText]
                let iconFamily = iconParts[0]
                let iconClass = iconParts[1]
                let iconText = iconParts[2]
                return {
                    family: iconFamily,
                    class: iconClass,
                    text: iconText
                }
            },
            onModalSelect(){
                $('#iconBrowserModal').modal('close')
            },
            onModalCancel(){
                const iconParts = this.getIconParts($perAdminApp.getNodeFromView('/state/iconbrowser/original'))
                // set selected icon to original icon
                $perAdminApp.getNodeFromView('/state/iconbrowser').family = iconParts.family
                $perAdminApp.getNodeFromView('/state/iconbrowser').class = iconParts.class
                $perAdminApp.getNodeFromView('/state/iconbrowser').text = iconParts.text
                $('#iconBrowserModal').modal('close')
            }
        }
    }
</script>
