const process   = require('process')
const fs        = require('fs')

const rollup    = require( 'rollup' )
const path      = require('path')
const vue       = require('rollup-plugin-vue')
const buble     = require('rollup-plugin-buble')
const camelcase = require('camelcase')

console.log('=== building vue files ========================================')

var basePath = './src/main/content/jcr_root/apps'
var distBasePath = './src/main/content/jcr_root/etc/felibs/examplesite'
function compileComponent(file){

    console.log("compiling vue file: .%s", file)
  // get component name from file name (file: a.vue, name: a)
  var name = file.substring(1, file.lastIndexOf('/')).toLowerCase().split('/').join('-')
  var nameCamelCase = camelcase(name)
  var nameCapitalCamelCase = nameCamelCase.charAt(0).toUpperCase() + nameCamelCase.slice(1)

  // each component needs a unique module name
  var moduleName = 'cmp'+nameCapitalCamelCase

  // compile the Vue component and give us a .js and .css
  rollup.rollup({
    entry: `${basePath}${file}`,
    plugins: [
      vue({
        compileTemplate: true,
        css: `${distBasePath}/css/${nameCamelCase}.css`
      }),
      buble()
    ]
  }).then( function(bundle) {

    bundle.write({
      format: 'iife',
      moduleName: moduleName,
      dest: `${distBasePath}/js/${nameCamelCase}.js`,
      globals: {
        tools: 'tools',
          log: 'log'
      }

    })
  })
  return { name: name, nameCamelCase: nameCamelCase, nameCapitalCamelCase: nameCapitalCamelCase}
}

function readDirs(basePath, path, extFilter) {
    var ret = new Array()
    var files = fs.readdirSync(path)
    files.forEach( function(file) {
        var filePath = path + '/' + file;
        if(filePath.endsWith(extFilter)) {
            ret.push(filePath.slice(basePath.length))
        }
        var stats = fs.statSync(filePath)
        if(stats.isDirectory()) {
            ret = ret.concat(readDirs(basePath, filePath, extFilter))
        }
    })
    return ret;
}

var vueFiles = readDirs(basePath, basePath, '.vue')

vueFiles.forEach( function(file) {

    compileComponent(file)

})

var jsFiles = readDirs(distBasePath+'/', distBasePath + '/js', '.js')
jsFiles.unshift('<!-- auto generated by build -->')
fs.writeFileSync(distBasePath+'/js.txt', jsFiles.join('\n'))

var cssFiles = readDirs(distBasePath+'/', distBasePath + '/css', '.css')
cssFiles.unshift('<!-- auto generated by build -->')
fs.writeFileSync(distBasePath+'/css.txt', cssFiles.join('\n'))